STEIN/STEIN/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('equipe.urls')),
    path('', include('estoque.urls')),
    path('', include('mesas.urls')),
    path('', include('usuarios.urls')),
    path('djangorestframeworkapi/', include('restAPI.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('enviar_email/', include('moduloEmail.urls')),
    re_path(r'^uploads/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT})
]

STEIN/paginas/urls.py
from django.urls import path
from .views import Modelo, Inicio, Formulario, Agradecimento

urlpatterns = [
    path('modelo/', Modelo.as_view(), name='model'),
    path('', Inicio.as_view(), name='index'),
    path('formulario/', Formulario.as_view(), name='form'),
    path('agradecimento/', Agradecimento.as_view(), name='agradecimento')
]

STEIN/equipe/models.py
from django.contrib.auth.models import User
from django.db import models as m
from django.utils import timezone
from django.core.exceptions import ValidationError

from colorfield.fields import ColorField

# Create your models here.
class Setor(m.Model):
    nome = m.CharField(max_length=50, unique=True)
    descricao = m.CharField(max_length=150, verbose_name='Descrição', blank=True, null=True)
    cor = ColorField(default='#808080')

    def __str__(self):
        return f'{self.nome}'

class Cargo(m.Model):
    setor = m.ForeignKey(Setor, on_delete=m.PROTECT, verbose_name='Setor')
    nome = m.CharField(max_length=50, unique=True)
    descricao = m.CharField(max_length=150, verbose_name='Descrição', blank=True, null=True)
    salario = m.DecimalField(max_digits=8, decimal_places=2, verbose_name='Salário')
    administrador = m.BooleanField(default=False)

    def __str__(self):
        return f'{self.nome} - {self.setor.nome} - R$ {self.salario}'


class Funcionario(m.Model):
    def validate_cpf(value):
        if len(value) < 14:
            raise ValidationError('CPF inválido.', code='cpfInválida')
    def validate_ctps(value):
        if len(value) < 11:
            raise ValidationError('CTPS inválida.', code='ctpsInválida')

    primeiro_nome = m.CharField(max_length=20, verbose_name='Primeiro Nome')
    segundo_nome = m.CharField(max_length=80, verbose_name='Sobrenome')
    cpf = m.CharField(max_length=14, unique=True, validators=[validate_cpf])
    ctps = m.CharField(max_length=14, unique=True, validators=[validate_ctps])
    dataNascimento = m.DateField(verbose_name='Data de Nascimento', default='01/01/2000')
    email = m.EmailField(blank=True)
    tel = m.CharField(max_length=15, verbose_name='Telefone', help_text='Com DDD.')
    rua = m.CharField(max_length=30, verbose_name='Rua ou Avenida')
    numero = m.IntegerField(verbose_name='Número')
    bairro = m.CharField(max_length=15, verbose_name='Bairro ou Jardim')
    cidade = m.CharField(max_length=30)
    funcao = m.ForeignKey(Cargo, on_delete=m.PROTECT, verbose_name='Função')
    bonusMensal = m.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Bônus Salarial Mensal')
    dataContratacao = m.DateField(default=timezone.now, verbose_name='Data de Contratação')
    observacao = m.CharField(max_length=255, null=True, blank=True, verbose_name='Observação')
    dataDemicao = m.DateField(null=True, blank=True, verbose_name='Data Demissional:')
    demitido = m.BooleanField(default=False, verbose_name='Demitido:')
    salTotal = m.DecimalField(blank=True, null=True, editable=False, decimal_places=2, max_digits=10, verbose_name='Salário Total')
    motivoDemicao = m.CharField(blank=True, null=True, max_length=100, verbose_name='Motivo da Demissão:')
    administrador = m.BooleanField(default=False)
    contaFuncionario = m.ForeignKey(User, null=True, blank=True, on_delete=m.PROTECT)

    def __str__(self):
        return f'{self.primeiro_nome} - {self.cpf} - {self.funcao.nome}'

STEIN/estoque/models.py
from django.db import models as m
from django.utils import timezone

# Create your models here.
class TipoProduto(m.Model):
    tipo = m.CharField(max_length=50, help_text='EX: Suco, Lanche, ...', unique=True)

    def __str__(self):
        return f'{self.tipo}'

class Produto(m.Model):
    tipoProduto = m.ForeignKey(TipoProduto, on_delete=m.PROTECT, verbose_name='Tipo do Produto')
    nome = m.CharField(max_length=60, unique=True)
    preco = m.DecimalField(max_digits=8, decimal_places=2)
    descricao = m.CharField(max_length=150, null=True, blank=True, verbose_name='Descrição')
    dataAdicao = m.DateField(editable=False, default=timezone.now)
    vendendo = m.BooleanField(default=True)
    imagem = m.ImageField(upload_to='images/produtos', null=True)

    def __str__(self):
        return f'{self.nome} - {self.tipoProduto.tipo} - R$ {self.preco}'

STEIN/mesas/models.py
from email.policy import default
from tkinter import CASCADE
from django.db import models as m
from django.utils import timezone
from django.core.exceptions import ValidationError


from moduloEmail.models import EmailAnonimo
from equipe.models import Funcionario
from estoque.models import Produto

# Create your models here.
class Mesa(m.Model):
    numero = m.IntegerField(verbose_name='Número da Mesa:')
    ocupada = m.BooleanField(default=False, blank=True)
    garcom = m.BooleanField(default=False, blank=True)

    def __str__(self):
        return f'{self.numero}'

class Comanda(m.Model):
    def validate_nmrMesa(value):
        try:
            tam = len(Comanda.objects.exclude(nmrMesa__lt=value).exclude(nmrMesa__gt=value).filter(encerrada=False).values())
        except:
            a = 1
        else:
            a = 0

        if tam != 0:
            raise ValidationError('A mesa já está ocupada', code='MesaOcupada')

    nmrMesa = m.ForeignKey(Mesa, on_delete=m.PROTECT, validators=[validate_nmrMesa])
    funcionario = m.ForeignKey(Funcionario, on_delete=m.PROTECT)
    produtos = m.ManyToManyField(Produto, through='Comanda_Produto')
    valorTotal = m.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, default=0)
    valorPago = m.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, default=0)
    atualizada = m.DateTimeField(auto_now=True)
    dataHoraCriada = m.DateTimeField(default=timezone.now, editable=False)
    dataCriada = m.DateField(auto_now_add=True, editable=False)
    encerrada = m.BooleanField(default=False)
    dataHoraEncerrada = m.DateTimeField(null=True, blank=True)
    observacao = m.CharField(null=True, blank=True, max_length=255)
    contaAnon = m.ForeignKey(EmailAnonimo, null=True, blank=True, on_delete=m.PROTECT)

    def __str__(self):
        return f'{self.nmrMesa} ({self.funcionario.primeiro_nome}) - {self.dataHoraCriada.date()} {self.dataHoraCriada.time()}'

class Comanda_Produto(m.Model):
    comanda = m.ForeignKey(Comanda, on_delete=m.CASCADE)
    produto = m.ForeignKey(Produto, on_delete=m.PROTECT)
    quantidade = m.IntegerField(default=1)
    quantidadeEntregue = m.IntegerField(default=0)
    horaPedido = m.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.comanda}'

STEIN/paginas/models.py
from django.db import models

# Create your models here.

STEIN/paginas/views.py
from django.views.generic import TemplateView
import mesas.models as mModels
import estoque.models as eModels
import datetime
import django.http as http

# Create your views here.
class Modelo(TemplateView):
    template_name = 'paginas/modelo.html'

class Inicio(TemplateView):
    template_name = 'paginas/inicio.html'
    def get_context_data(self, **kwargs):
        cont = super().get_context_data(**kwargs)

        # FILTRAR PRODUTOS PEDIDOS DE DIA DE HOJE - 30 DIAS.
        
        return cont

class Formulario(TemplateView):
    template_name = 'paginas/form.html'

class Agradecimento(TemplateView):
    template_name = 'paginas/modelo.html'

STEIN/paginas/templates/paginas/listas/comandas.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load mathfilters %}

{% block titulo %}
Lista de Comandas
{% endblock %}

{% block conteudo %}
<div class="table mt-3 text-center">
    <table class="table">
        <tr>
            <td>
                <h3>Listagem de todas as comandas criadas.</h3>
            </td>

            <td>
                <a href="{% url 'cad-comanda' %}" class="btn btn-primary btn-sm">
                    <i class="fa fa-plus-square" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
    </table>
    <form action="?" method="GET" class="mb-2">
        <div class="row">
            <div class="col">
                <select id="encerrado" name="encerrado" placeholder="Comandas:">
                    {% if request.GET.encerrado|slugify == True|slugify %}
                    <option value="True" selected> Abertas </option>
                    {% elif request.GET.encerrado|slugify == 'none' %}
                    <option value="True" selected> Abertas </option>
                    {%else%}
                    <option value="True"> Abertas </option>
                    {% endif %}
                    {% if request.GET.encerrado|slugify == False|slugify %}
                    <option value="False" selected> Encerradas </option>
                    {% else %}
                    <option value="False"> Encerradas </option>
                    {% endif %}
                </select>
            </div>
            <div class="col">
                <input type="date" name="dataAbertura" id="dataAbertura" value="{{request.GET.dataAbertura|slugify}}">
            </div>

            <div class="col text-end">
                <button type="submit" class="btn btn-primary">Buscar</button>

                <a href="{% url 'listar-comanda' %}" class="btn btn-secondary">Limpar</a>
            </div>
        </div>
    </form>
    {% for obj in object_list.0 %}
    {% if obj.encerrada %}
    <div class="accordion accordion-flush mb-2" id="accordionFlush{{obj.pk}}"
        style="border: 2px solid rgb(117, 8, 8); border-radius: 5px;">
        {% else %}
        <div class="accordion accordion-flush mb-2" id="accordionFlush{{obj.pk}}"
            style="border: 2px solid rgb(17, 117, 8); border-radius: 5px;">
            {%endif%}
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-heading{{obj.pk}}">
                    <button class="collapsed accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapse{{obj.pk}}" aria-expanded="false"
                        aria-controls="flush-collapse{{obj.pk}}">
                        <b>Mesa:</b> <span style='margin-left: 5px;'> {{obj.nmrMesa}} - {{obj.dataHoraCriada}} - Valor
                            Total: R${{obj.valorTotal}}</span>
                    </button>
                </h2>

                <div id="flush-collapse{{obj.pk}}" class="accordion-collapse collapse"
                    aria-labelledby="flush-heading{{cargo.pk}}" data-bs-parent="#accordionFlush{{obj.pk}}">
                    <div class="accordion-body" style="margin-left: 50px;">
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Produtos:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                {% for prod in obj.produtos.all %}
                                {% for pedido in object_list.1 %}
                                {% if obj.pk == pedido.comanda_id and prod.pk == pedido.produto_id %}
                                <span class="row mb-2" style="border: 1px solid rgb(58, 58, 58); border-radius:10px;">
                                    <span class="col">{{prod.nome}}</span>
                                    <span class="col">{{pedido.quantidade}} x R${{prod.preco}} = <span
                                            class="text-success">R${{prod.preco|mul:pedido.quantidade}}</span></span>
                                </span>
                                {% endif %}
                                {% endfor %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Observação:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                {% if obj.observacao == ' ' %}
                                Não há observações.
                                {% elif obj.observacao != Null %}
                                {{obj.observacao}}
                                {% else %}
                                Não há observações.
                                {% endif %}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Total:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                R${{obj.valorTotal}}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Valor Pago:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                R${{obj.valorPago}}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Valor Restante:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                R${{obj.valorTotal|sub:obj.valorPago}}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Funcionário:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                {{obj.funcionario.primeiro_nome}} {{obj.funcionario.segundo_nome}} -
                                {{obj.funcionario.funcao.nome}}
                            </div>
                        </div>
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Data:</b></div>
                            <div class="col-md-8" style="margin-left: 15px;">
                                {{obj.dataHoraCriada}}
                            </div>
                        </div>

                    </div>
                    <div class="row justify-content-around text-center">
                        {% if perms.mesas.delete_comanda %}
                        <div class="col-sm-2">
                            <a class="btn btn-danger btn" href="{% url 'del-comanda' obj.pk %}">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                                Excluir</a>
                        </div>
                        {% endif %}
                        {% if not obj.encerrada and perms.mesas.change_comanda %}
                        <div class="col-sm-2">
                            <button type="button" class="btn btn-success" data-bs-toggle="modal"
                                data-bs-target="#exampleModal{{obj.nmrMesa}}">
                                <i class="fa fa-money" aria-hidden="true"></i>
                                Pagar / Encerrar
                            </button>
                        </div>
                        {% endif %}
                        <!-- {% if obj.nmrMesa.garcom != 0 %}
                        <div class="col-sm-2" id="chamadoGarcom">
                            <button type="button" class="btn btn-warning"
                                onclick="atenderChamado('{{obj.nmrMesa.id}}');">
                                <i class="fa fa-check" aria-hidden="true"></i>
                                Chamado Atendido
                            </button>
                        </div>
                        {% endif %} -->
                        {% if perms.mesas.change_comanda %}
                        <div class="col-sm-2">
                            <a class="btn btn-primary btn" href="{% url 'edit-comProd' obj.pk %}">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                                Editar</a>
                        </div>
                        {% endif %}
                    </div>
                    {% if not obj.encerrada %}
                    <div class="modal fade" id="exampleModal{{obj.nmrMesa}}" tabindex="-1"
                        aria-labelledby="exampleModalLabel{{obj.nmrMesa}}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel{{obj.nmrMesa}}">Pagar/Encerrar
                                    </h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="row justify-content-around ">
                                        <div class="col text-center">
                                            <strong>Total</strong><br>
                                            R${{obj.valorTotal}}
                                        </div>
                                        <div class="col text-center">
                                            <strong>Valor Pago</strong><br>
                                            <input type="text" id="valPago{{obj.pk}}" value="{{obj.valorPago}}">
                                        </div>
                                        <div class="col text-center">
                                            <strong>Encerrar</strong><br>
                                            <input type="checkbox" id="enc{{obj.pk}}">
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Fechar</button>
                                    <button type="button" class="btn btn-primary"
                                        onclick="Salvar('{{obj.pk}}')">Salvar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    <hr>
                </div>
            </div>
        </div>
        {% empty %}
        <p>Não há comandas abertas no sistema.</p>
        {% endfor %}

    </div>

    <script>
        function Salvar(comandaPK) {
            encerrar = false
            if ($('#enc' + comandaPK).is(":checked")) {
                encerrar = true
            }
            valPago = $('#valPago' + comandaPK).val()
            $.ajax({
                type: "GET",
                url: "{% url 'atualizarPagComanda' %}",
                data: {
                    encerrada: encerrar,
                    valorPago: valPago,
                    comandaPK: comandaPK
                },
                success: function (response) {
                    window.location.replace('{% url "listar-comanda" %}');
                }
            });
        }
    </script>
    {% endblock %}

STEIN/paginas/templates/paginas/listas/produto.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
Lista de Produtos
{% endblock %}

{% block conteudo %}

<div class="table mt-3 text-center">
    <table class="table">
        <tr>
            <td>
                <h3>Listagem de todos os produtos registrados.</h3>
            </td>
            {% if not request.user.is_anonymous and perms.estoque.add_produto %}
                <td>
                    <a href="{% url 'cad-produto' %}" class="btn btn-primary btn-sm">
                        <i class="fa fa-plus-square" aria-hidden="true"></i>
                    </a>
                </td>
            {% endif %}
        </tr>
    </table>
    {% if perms.equipe.view_funcionario %}
    <div class="accordion accordion-flush mb-2" style="border: 2px solid black; border-radius:20px;"
    id="accordionFlushMenosPedidos">
    <div class="accordion-item" style="border-radius:105px;">
        <h4 class="accordion-header" id="flush-MaisPedidos">
        <button type="button" class="accordion-button collapsed" style="border-radius:105px;" data-bs-toggle="collapse"
            data-bs-target="#flush-collapseMVendidos" aria-expanded="false" aria-controls="collapseOne">
            Mais Pedidos nos Últimos 30 dias
        </button>
        </h4>
        <div id="flush-collapseMVendidos" class="accordion-collapse collapse" aria-labeled-by="flush-headingOne"
        data-bs-parent="accordionFlushMaisPedidos">
        <div class="accordion-body">
            <table class="table">
            <thead>
                <tr>
                <th scope="col">Lugar</th>
                <th scope="col">Produto</th>
                <th scope="col">Quantidade</th>
                </tr>
                <tr>
            </thead>
            <tbody>
                {% for pedido in object_list.2.prodMPedidos %}
                {% if forloop.counter <= 10 %} <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{pedido.produto.nome}}</td>
                <td>{{pedido.quantidade}}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
            </table>
        </div>
        </div>
    </div>
    </div>
    {% endif %}

    <div id="carouselProdutos" class="carousel slide user-select-none" data-bs-interval="false"
        data-bs-touch="false">
        <div class="list-group list-group-horizontal text-nowrap overflow-auto sticky-top" 
            style=" background-color: white;;padding-top: 3px;">
            {% for tipo in object_list.1 %}
                <button type="button" data-bs-target="#carouselProdutos" 
                        data-bs-slide-to={{forloop.counter|add:'-1'}} 
                        class="col btn btn-sm mb-2 botTipo" 
                        aria-current="true" aria-label="Slide {{forloop.counter}}" 
                        style="border: 1px solid gray; margin-right: 5px; {%if forloop.counter == 1 %} background-color:blue !important; color:white !important; {%endif%}"
                        id="tipo{{tipo.pk}}">
                        {{tipo.tipo}}
                </button>
                <script>
                    $("#tipo{{tipo.pk}}").click(function () { 
                        $('.botTipo').attr('style', 'border: 1px solid gray; margin-right: 5px;');
                        $("#tipo{{tipo.pk}}").attr('style', 'border: 1px solid gray; margin-right: 5px; background-color: blue !important; color: white !important;');
                    });
                </script>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for tipo in object_list.1 %}
                {% if forloop.counter == 1 %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item mt-3">
                {%endif%}
                        {% for produto in object_list.0 %}
                            {% if produto.tipoProduto == tipo %}
                            <div class="row mb-2 align-items-center" id="card{{produto.pk}}"
                                 style="margin-left: 2%; margin-right: 2%; border: 5px solid {% if produto.vendendo %} green {% else %} red {% endif %}; border-radius: 25px;" >
                                <div class="col-sm-4">
                                    {% if produto.imagem %}
                                        <img src="{{produto.imagem.url}}" class="mb-1 mt-1 mx-auto" width="150px" style="border: 5px; border-radius: 15px;">
                                    {% else %}
                                        <img src="{% static 'img/semIMG.png' %}" class="mb-1 mt-1 mx-auto" width="150px" style="border: 5px; border-radius: 15px;">
                                    {% endif %}
                                </div>
                                <div class="col-sm-5">
                                    <h3>{{produto.nome}}</h3>
                                    {% if produto.descricao %}
                                        {{produto.descricao}}
                                    {% endif %}
                                    <br>
                                    R${{produto.preco}} cada
                                </div>
                                <div class="col mb-2">
                                    <div class="row mb-4 mt-3">
                                        <div class="col">
                                            {% if request.user.is_staff %}
                                            <a href="{% url 'edit-produto' produto.pk %}">
                                                <button type="button" class="btn btn-primary btn-lg" >
                                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                                    Editar
                                                </button>
                                            </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            {% if request.user.is_staff %}
                                            <a href="{% url 'del-produto' produto.pk %}">
                                                <button type="button" class="btn btn-danger btn-lg">
                                                    <i class="fa fa-close" aria-hidden="true"></i>
                                                    Excluir
                                                </button>
                                            </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>                                    
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

STEIN/paginas/templates/paginas/listas/tipoProduto.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
Lista dos TIpos de Produtos
{% endblock %}

{% block conteudo %}

<div class="table mt-3 text-center">
    <table class="table">
        <tr>
            <td>
                <h3>Listagem de todos os tipos de produtos registrados</h3>
            </td>

            <td>
                <a href="{% url 'cad-tProduto' %}" class="btn btn-primary btn-sm">
                    <i class="fa fa-plus-square" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
    </table>
    {% for obj in object_list %}
        <div class="accordion accordion-flush " id="accordionFlush{{obj.pk}}">
            <div class="accordion-item mb-2" style="background-color: white; border-left: 2px solid black; border-right: 2px solid black;">
                <h2 class="accordion-header" id="flush-heading{{obj.pk}}">
                    <button class="accordion-button collapsed"
                    type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{obj.pk}}"
                    aria-expanded="false" aria-controls="flush-collapse{{obj.pk}}">
                    {{obj.tipo}}
                    </button>
                </h2>
                
                <div id="flush-collapse{{obj.pk}}" class="accordion-collapse collapse" 
                aria-labelledby="flush-heading{{obj.pk}}" data-bs-parent="#accordionFlush{{obj.pk}}">
                    <div class="accordion-body" style="margin-left: 50px;">
                        <div class="row text-start">
                            <div class="col-sm-2"><b>Descrição:</b></div>
                            {% if obj.descricao != Null %}
                            <div class="col-md-8" style="margin-left: 15px;">{{obj.descricao}}</div>
                            {% else %}
                            <div class="col-md-8" style="margin-left: 15px;">Não há descrição.</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row justify-content-md-center">

                        {% if perms.estoque.delete_tipoproduto %}
                        <div class="col-md-3">
                            <a class="btn btn-danger btn" href="{% url 'del-tProduto' obj.pk %}">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                                Excluir</a>
                        </div>
                        {% endif %}
                        {% if perms.estoque.change_tipoproduto %}
                        <div class="col-md-3">
                            <a class="btn btn-primary btn" href="{% url 'edit-tProduto' obj.pk %}">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                                Editar</a>
                        </div>
                        {% endif %}
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    {% empty %}
        <p>Não há tipos de produtos cadastrados no sistema, por favor, adicione um.</p>
    {% endfor %}

</div>
{% endblock %}