STEIN/STEIN/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('equipe.urls')),
    path('', include('estoque.urls')),
    path('', include('mesas.urls')),
    path('', include('usuarios.urls')),
    path('djangorestframeworkapi/', include('restAPI.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('enviar_email/', include('moduloEmail.urls')),
    re_path(r'^uploads/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT})
]

STEIN/paginas/urls.py
from django.urls import path
from .views import Modelo, Inicio, Formulario, Agradecimento

urlpatterns = [
    path('modelo/', Modelo.as_view(), name='model'),
    path('', Inicio.as_view(), name='index'),
    path('formulario/', Formulario.as_view(), name='form'),
    path('agradecimento/', Agradecimento.as_view(), name='agradecimento')
]

STEIN/equipe/models.py
from django.contrib.auth.models import User
from django.db import models as m
from django.utils import timezone
from django.core.exceptions import ValidationError

from colorfield.fields import ColorField

# Create your models here.
class Setor(m.Model):
    nome = m.CharField(max_length=50, unique=True)
    descricao = m.CharField(max_length=150, verbose_name='Descrição', blank=True, null=True)
    cor = ColorField(default='#808080')

    def __str__(self):
        return f'{self.nome}'

class Cargo(m.Model):
    setor = m.ForeignKey(Setor, on_delete=m.PROTECT, verbose_name='Setor')
    nome = m.CharField(max_length=50, unique=True)
    descricao = m.CharField(max_length=150, verbose_name='Descrição', blank=True, null=True)
    salario = m.DecimalField(max_digits=8, decimal_places=2, verbose_name='Salário')
    administrador = m.BooleanField(default=False)

    def __str__(self):
        return f'{self.nome} - {self.setor.nome} - R$ {self.salario}'


class Funcionario(m.Model):
    def validate_cpf(value):
        if len(value) < 14:
            raise ValidationError('CPF inválido.', code='cpfInválida')
    def validate_ctps(value):
        if len(value) < 11:
            raise ValidationError('CTPS inválida.', code='ctpsInválida')

    primeiro_nome = m.CharField(max_length=20, verbose_name='Primeiro Nome')
    segundo_nome = m.CharField(max_length=80, verbose_name='Sobrenome')
    cpf = m.CharField(max_length=14, unique=True, validators=[validate_cpf])
    ctps = m.CharField(max_length=14, unique=True, validators=[validate_ctps])
    dataNascimento = m.DateField(verbose_name='Data de Nascimento', default='01/01/2000')
    email = m.EmailField(blank=True)
    tel = m.CharField(max_length=15, verbose_name='Telefone', help_text='Com DDD.')
    rua = m.CharField(max_length=30, verbose_name='Rua ou Avenida')
    numero = m.IntegerField(verbose_name='Número')
    bairro = m.CharField(max_length=15, verbose_name='Bairro ou Jardim')
    cidade = m.CharField(max_length=30)
    funcao = m.ForeignKey(Cargo, on_delete=m.PROTECT, verbose_name='Função')
    bonusMensal = m.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Bônus Salarial Mensal')
    dataContratacao = m.DateField(default=timezone.now, verbose_name='Data de Contratação')
    observacao = m.CharField(max_length=255, null=True, blank=True, verbose_name='Observação')
    dataDemicao = m.DateField(null=True, blank=True, verbose_name='Data Demissional:')
    demitido = m.BooleanField(default=False, verbose_name='Demitido:')
    salTotal = m.DecimalField(blank=True, null=True, editable=False, decimal_places=2, max_digits=10, verbose_name='Salário Total')
    motivoDemicao = m.CharField(blank=True, null=True, max_length=100, verbose_name='Motivo da Demissão:')
    administrador = m.BooleanField(default=False)
    contaFuncionario = m.ForeignKey(User, null=True, blank=True, on_delete=m.PROTECT)

    def __str__(self):
        return f'{self.primeiro_nome} - {self.cpf} - {self.funcao.nome}'

STEIN/estoque/models.py
from django.db import models as m
from django.utils import timezone

# Create your models here.
class TipoProduto(m.Model):
    tipo = m.CharField(max_length=50, help_text='EX: Suco, Lanche, ...', unique=True)

    def __str__(self):
        return f'{self.tipo}'

class Produto(m.Model):
    tipoProduto = m.ForeignKey(TipoProduto, on_delete=m.PROTECT, verbose_name='Tipo do Produto')
    nome = m.CharField(max_length=60, unique=True)
    preco = m.DecimalField(max_digits=8, decimal_places=2)
    descricao = m.CharField(max_length=150, null=True, blank=True, verbose_name='Descrição')
    dataAdicao = m.DateField(editable=False, default=timezone.now)
    vendendo = m.BooleanField(default=True)
    imagem = m.ImageField(upload_to='images/produtos', null=True)

    def __str__(self):
        return f'{self.nome} - {self.tipoProduto.tipo} - R$ {self.preco}'

STEIN/mesas/models.py
from email.policy import default
from tkinter import CASCADE
from django.db import models as m
from django.utils import timezone
from django.core.exceptions import ValidationError


from moduloEmail.models import EmailAnonimo
from equipe.models import Funcionario
from estoque.models import Produto

# Create your models here.
class Mesa(m.Model):
    numero = m.IntegerField(verbose_name='Número da Mesa:')
    ocupada = m.BooleanField(default=False, blank=True)
    garcom = m.BooleanField(default=False, blank=True)

    def __str__(self):
        return f'{self.numero}'

class Comanda(m.Model):
    def validate_nmrMesa(value):
        try:
            tam = len(Comanda.objects.exclude(nmrMesa__lt=value).exclude(nmrMesa__gt=value).filter(encerrada=False).values())
        except:
            a = 1
        else:
            a = 0

        if tam != 0:
            raise ValidationError('A mesa já está ocupada', code='MesaOcupada')

    nmrMesa = m.ForeignKey(Mesa, on_delete=m.PROTECT, validators=[validate_nmrMesa])
    funcionario = m.ForeignKey(Funcionario, on_delete=m.PROTECT)
    produtos = m.ManyToManyField(Produto, through='Comanda_Produto')
    valorTotal = m.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, default=0)
    valorPago = m.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, default=0)
    atualizada = m.DateTimeField(auto_now=True)
    dataHoraCriada = m.DateTimeField(default=timezone.now, editable=False)
    dataCriada = m.DateField(auto_now_add=True, editable=False)
    encerrada = m.BooleanField(default=False)
    dataHoraEncerrada = m.DateTimeField(null=True, blank=True)
    observacao = m.CharField(null=True, blank=True, max_length=255)
    contaAnon = m.ForeignKey(EmailAnonimo, null=True, blank=True, on_delete=m.PROTECT)

    def __str__(self):
        return f'{self.nmrMesa} ({self.funcionario.primeiro_nome}) - {self.dataHoraCriada.date()} {self.dataHoraCriada.time()}'

class Comanda_Produto(m.Model):
    comanda = m.ForeignKey(Comanda, on_delete=m.CASCADE)
    produto = m.ForeignKey(Produto, on_delete=m.PROTECT)
    quantidade = m.IntegerField(default=1)
    quantidadeEntregue = m.IntegerField(default=0)
    horaPedido = m.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.comanda}'

STEIN/paginas/models.py
from django.db import models

# Create your models here.

STEIN/paginas/views.py
from django.views.generic import TemplateView
import mesas.models as mModels
import estoque.models as eModels
import datetime
import django.http as http

# Create your views here.
class Modelo(TemplateView):
    template_name = 'paginas/modelo.html'

class Inicio(TemplateView):
    template_name = 'paginas/inicio.html'
    def get_context_data(self, **kwargs):
        cont = super().get_context_data(**kwargs)

        # FILTRAR PRODUTOS PEDIDOS DE DIA DE HOJE - 30 DIAS.
        
        return cont

class Formulario(TemplateView):
    template_name = 'paginas/form.html'

class Agradecimento(TemplateView):
    template_name = 'paginas/modelo.html'

STEIN/paginas/templates/paginas/agradecimento.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
Obrigado!
{% endblock %}

STEIN/paginas/templates/paginas/demitir.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% block titulo %}
Demitir Funcionário
{% endblock %}

{% block conteudo %}

<form action="" method="POST" class="text-center">
    <p class="text-danger text-center">
        <i class="fa fa-warning" aria-hidden="true"></i> Esta ação pode ser revertida <i class="fa fa-warning" aria-hidden="true"></i>
    </p>

    {% csrf_token %}

    {{ form.as_p }}

    <br>
    <p>Você realmente deseja demitir o funcionário?</p>

    <div class="container row">
        <div class="text-start col">
            <a class="btn btn-danger" href="{% url 'listar-funcionario' %}">
                Não
            </a>
        </div>

        <div class="text-end col">
            <button type="submit" class="btn btn-success">
                Sim
            </button>
        </div>
    </div>
</form>
{% endblock %}

{% block script %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_demitido').prop('checked', true);
        $('p>#id_demitido').hide();
        $('#id_dataDemicao').prop('required', true);
        $('#id_motivoDemicao').addClass('form-control');
        $('#id_dataDemicao').addClass('form-control')
        $('#id_dataDemicao').get(0).type = 'date';
    });
</script>
{% endblock %}

STEIN/paginas/templates/paginas/fontes.html
{% extends 'paginas/modelo.html' %}

<a href='https://dryicons.com/icon/frankenstein-icon-10169'> Ícone </a>
<a href="https://jscolor.com/"> jscolor.com </a>

STEIN/paginas/templates/paginas/form-excluir.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
{{titulo}}
{% endblock %}

{% block destaque %}
{% endblock %}

{% block conteudo %}
<p class="lead text-center">
    Você realmente deseja excluir o registro?
</p>

<hr>

<form action="" method="POST" class="text-center">

    <p>
        Registro: 
        <br>
        <h3 class="text-break"><b>{{ object }}</b></h3>        
    </p>

    {% csrf_token %}

    {{ form.as_p }}

    <br>
    <p class="text-danger">
        <i class="fa fa-warning" aria-hidden="true"></i>
        {% if not object.tipoProduto%}
        Atenção, esta ação não pode ser desfeita. 
        {%else%}
        Atenção, caso o produto esteja em uma comanda não será possível excluir o produto, ao invés disso, desmarque a opção 'Vendendo' no menu editar.
        {%endif%}
        <i class="fa fa-warning" aria-hidden="true"></i>
    </p>

    <div class="container row">
        <div class="text-start col">
            <button type="button" class="btn btn-primary"
            onclick="history.back()">
                <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>
                Voltar
            </button>
        </div>

        <div class="text-end col">
            <button type="submit" class="btn btn-danger" scale>
                <i class="fa fa-trash" aria-hidden="true"></i>
                Excluir
            </button>
        </div>
    </div>

</form>
{% endblock %}

STEIN/paginas/templates/paginas/inicio.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
Tela Inicial
{% endblock %}


{% block conteudo %}
<h2>Seja Bem Vindo(a)!</h2>

<div class="col-md-10 mx-auto">
  <div class="row justify-content-around">
    {% if request.user.is_staff or request.user.is_superuser or perms.mesas.add_comanda%}
    <div class="btn btn-outlined-secondary card mb-2" style="width: 17rem; margin-right: 10px;" 
    onmouseenter="this.style = 'width: 17rem; margin-right: 10px;background-color: lightgray !important;'" 
    onmouseleave="this.style = 'width: 17rem; margin-right: 10px;background-color: white !important; color: black !important;'"
    onclick="{%if request.user.is_staff or reqest.user.is_superuser%}window.location.assign('{% url "listar-comanda" %}'){%else%}window.location.assign('{% url "gerencia-comanda" %}'){%endif%} ">
      <img src="{% static 'img/garcomPedidos.jpg' %}" class="card-img-top mt-2" alt="..." style="max-height: 150px;"
      style="max-width: 250px;">
      <div class="card-body">
        <h5 class="card-title">Verificar Comandas</h5>
        {% if request.user.is_staff %}
        <p class="card-text">Listagem de comandas abertas e/ou fechadas.</p>
        {% else %}
        <p class="card-text">Menu de mesas para a criação de comandas.</p>
        {% endif %}
      </div>
    </div>
    {%endif%}
    <div class="btn btn-outlined-secondary card mb-2" style="width: 17rem; margin-right: 10px;" 
    onmouseenter="this.style = 'width: 17rem; margin-right: 10px;background-color: lightgray !important;'" 
    onmouseleave="this.style = 'width: 17rem; margin-right: 10px;background-color: white !important; color: black !important;'"
    onclick="window.location.assign('{% url "listar-produto" %}')">
      <img src="{% static 'img/cardapio.jpg' %}" class="card-img-top mt-2 mx-auto" alt="Homem segurando um cardápio" 
      style="max-width: 250px;">
      <div class="card-body">
        <h5 class="card-title">Menu</h5>
        <p class="card-text">Aqui você pode olhar todos os produtos que temos no cardápio!</p>
      </div>
    </div>
    {% if not request.user.is_anonymous %}
    {% if perms.mesas.add_comanda or request.user.is_staff or request.user.is_superuser %}
    <div class="btn btn-outlined-secondary card mb-2" style="width: 17rem; margin-right: 10px;" 
    onmouseenter="this.style = 'width: 17rem; margin-right: 10px;background-color: lightgray !important;'" 
    onmouseleave="this.style = 'width: 17rem; margin-right: 10px;background-color: white !important; color: black !important;'"
    onclick="window.location.assign('{% url "cad-comanda" %}')">
      <img src="{% static 'img/fazerPedido.jpg' %}" class="card-img-top mt-2"
        alt="Pessoa com uma caneta na mão anotando em um caderno.">
      <div class="card-body">
        <h5 class="card-title">Fazer Pedido</h5>
        <p class="card-text"> Criado para que a linha de frente crie as comandas dos clientes. </p>
      </div>
    </div>
    {% endif %}
    {% else %}
    <div class="text-center card mb-2" style="width: 17rem; margin-right: 10px;">
      <img src="{% static 'img/pedido.jpg' %}" class="card-img-top mt-2" alt="Homem segurando uma comanda" 
      style="max-width: 250px;">
      <div class="card-body">
        <h5 class="card-title">Pedido</h5>
        <p class="card-text">Aqui você pode olhar e alterar seu pedido.</p>
        <script>
          function verificaPedido() {
            if ($('#codeVerify').val() == '') {
              $('#codeVerify').attr('style', 'border: 1px solid red;').attr('value', 'Insira um código Válido')
            } else {
              $.ajax({
                type: "GET",
                url: "{% url 'enviarCodigoUnicoMail' %}",
                data: {
                  code: $('#codeVerify').val(),
                  ident: '0',
                },
                success: function (response) {
                  window.location.href = response
                },
                error: function (response) {
                }
              });
            }
          }
        </script>
        <div class="text-center">
          <input type="text" name="codigoUsuario" class='form-control' id="codeVerify" placeholder="Código do email"
            onclick="$('#codeVerify').attr('style', '').attr('value', '')"> <br>
          <button type="button" class="btn btn-primary" onclick="verificaPedido()">Ver Pedido</button>
        </div>
      </div>
    </div>
    {% endif %}
    {% if perms.equipe.view_funcionario or request.user.is_staff or request.user.is_superuser %}
    <div class="btn btn-outlined-secondary card mb-2" style="width: 17rem; margin-right: 10px;" 
    onmouseenter="this.style = 'width: 17rem; margin-right: 10px;background-color: lightgray !important;'" 
    onmouseleave="this.style = 'width: 17rem; margin-right: 10px;background-color: white !important; color: black !important;'"
    onclick="window.location.assign('{% url "listar-funcionario" %}')">
      <img src="{% static 'img/equipe.png' %}" class="card-img-top mt-2"
        alt="desenhos de pessoas umas ao lado das outras."
        style="max-width: 250px;">
      <div class="card-body">
        <h5 class="card-title">Gerenciar Equipe</h5>
        <p class="card-text">Gerenciamento de todos os colaboradores que trabalham, ou já trabalharam, no restaurante.
        </p>
      </div>
    </div>
    {%endif%}

    {% if perms.mesas.view_comanda or request.user.is_staff or request.user.is_superuser %}
    <div class="btn btn-outlined-secondary card mb-2" style="width: 17rem; margin-right: 10px;" 
    onmouseenter="this.style = 'width: 17rem; margin-right: 10px;background-color: lightgray !important;'" 
    onmouseleave="this.style = 'width: 17rem; margin-right: 10px;background-color: white !important; color: black !important;'"
    onclick="window.location.assign('{% url "listar-retaguarda" %}')">
      <img src="{% static 'img/retaguarda.jpeg' %}" class="card-img-top mt-2"
        alt="desenhos de pessoas umas ao lado das outras."
        style="max-width: 250px;">
      <div class="card-body">
        <h5 class="card-title">Comandas da Cozinha</h5>
        <p class="card-text">Exibição das comandas próprias para a retaguarda.</p>
      </div>
    </div>
    {%endif%}
  </div>
</div>
{% endblock %}

STEIN/paginas/templates/paginas/modelo-listas.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
    {% block pagina-titulo %}

    {% endblock %}
{% endblock %}

{% block conteudo %}

<div class="mt-3 text-center">
    <div class="row justify-content-evenly">
        <div class="col">
            <h3>
                {% block lista-titulo %}
                    Titulo da Lista
                {% endblock %}
            </h3>
        </div>
        <div class="col-md-1">
            <a href="{% block url-add %}{% endblock %}" class="btn btn-primary btn-sm">
                <i class="fa fa-plus-square" aria-hidden="true"></i>
            </a>
        </div>
    </div>

    <hr>
    <div class="table table-responsive">
        <table class="table table-hover">
            <tr>
                {% block tabela-header %}
                {% endblock %}
            </tr>
            
            {%}
        </table>
    </div>
</div>

{% endblock %}

STEIN/paginas/templates/paginas/modelo.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- IMPORTAÇÃO DO AWESOMEFONTS-->
    <link rel="stylesheet" href="{% static 'fontawesome6/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome6/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome6/css/solid.css' %}">
    <!-- IMPORTAÇÃO DE ARQUIVOS ESTÁTICOS-->

    <!-- ÍCONE -->
    {% block icone %}
    <link rel="icon" href="{% static 'img/stein_ico.png' %}">
    {% endblock %}

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>
        {% block titulo %}
        MODELO
        {% endblock %}
    </title>
    {% block scriptHeader %}
    {% endblock %}
    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
</head>

<body>
    {% block menu %}
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static 'img/stein_ico.png' %}" alt="Ícone em formato de cabeça de Frankstein" width="40px">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">
                            <div class="navbar-text">
                                <i class="fa fa-home" aria-hidden="true"></i>
                                Inicio
                            </div>
                        </a>
                    </li>

                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="dropdown nav-link" href="" data-bs-toggle="dropdown" aria-expanded="false">
                                <div class="navbar-text">
                                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                                    Colaboradores
                                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                                </div>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'listar-funcionario' %}">
                                        Funcionarios
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'listar-cargo' %}">
                                        Cargos
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'listar-setor' %}">
                                        Setores
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        {% if not request.user.is_anonymous %}
                        <div class="dropdown">
                            <a class="dropdown nav-link" href="" data-bs-toggle="dropdown" aria-expanded="false">
                                <div class="navbar-text">
                                <i class="fa fa-box" aria-hidden="true"></i>
                                Produtos
                                <i class="fa fa-angle-down" aria-hidden="true"></i>
                                </div>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'listar-produto' %}">
                                        Produtos
                                    </a>
                                </li>
                                <li>
                                    {% if perms.estoque.view_tipoproduto %}
                                    <a class="dropdown-item" href="{% url 'listar-tProduto' %}">
                                        Tipos de Produtos
                                    </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                        {% else %}
                        <a class="nav-link" href="{% url 'listar-produto' %}">
                            <div class="navbar-text">   
                            <i class="fa fa-box" aria-hidden="true"></i>
                            Produtos
                            </div>  
                        </a>
                        {% endif %}
                    </li>
                    {% if perms.mesas.add_comanda or request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gerencia-comanda' %}">
                            <div class="navbar-text">
                            <i class="fa fa-sticky-note" aria-hidden="true"></i>
                            Comandas
                            </div>
                        </a>
                    </li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listar-comanda' %}">
                            <div class="navbar-text">
                            <i class="fa fa-book" aria-hidden="true"></i>
                            Gerenciamento de Comandas
                            </div>
                        </a>
                    </li>
                    {% endif %}
                    <span id="comRet">
                        <input type="checkbox" hidden name="" id="chkbxRetaguarda">
                    </span>
                    {% for grupo in request.user.groups.all %}
                    {% if grupo.name == 'Retaguarda' and perms.mesas.view_comanda or request.user.is_staff or request.user.is_superuser %}
                    <script type="text/javascript">
                        if ($('#chkbxRetaguarda').is(':checked') == false) {
                            $('#comRet').append('<li class="nav-item"><a class= "nav-link" href = "{% url "listar-retaguarda" %}" ><div class="navbar-text"><i class="fa fa-kitchen-set" aria-hidden="true"></i>Comandas / Retaguarda</div></a></li>');
                            $('#chkbxRetaguarda').prop('checked', true);
                        }
                    </script>
                    {% endif %}
                    {% endfor %}
                    {% if request.user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cad-comanda' %}">
                            <div class="navbar-text">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                            Fazer Pedido
                            </div>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <div class="dropdown navbar-nav" style="padding-right: 30px;" id="usuario">

                    {% if request.user.is_authenticated %}
                    <a class="dropdown nav-item nav-link" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <div class="navbar-text">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        {% if user.first_name %}
                        {{user.first_name}}
                        {% else %}
                        {{user.username}}
                        {% endif %}
                        <i class="fa fa-angle-down" aria-hidden="true"></i>
                        </div>
                    </a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'sair' %}">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Sair
                            </a>
                        </li>
                    </ul>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'entrar' %}">
                        <div class="navbar-text">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>
                        Logar
                        </div>
                    </a>
                    {% endif %}
                </div>
            </div>

        </div>
    </nav>
    {% endblock %}

    <div class="content">
        {% block corpo %}
        <div class="container mt-2">
            <div class="row">
                <div class="col">

                </div>
                <div class="col-20">
                    {% block conteudo %}

                    {% endblock %}
                </div>
                <div class="col">
                </div>
            </div>
            <div class="push"></div>
        </div>
        {% endblock %}
    </div>

    {% block rodape %}
    <footer class="footer bg-dark text-center text-light justify-content-center">
        <p style="padding-top: 0.85%;">Desenvolvido por Vitor Garcia, Rafael Leonardo e Giovana Garcia.</p>
    </footer>
    {% endblock %}


    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/fontAwesome.js' %}" crossorigin="anonymous"></script>

    {% block script %}

    {% endblock %}
</body>

</html>